#!/bin/bash

#    proteus-apt-url
#
#    Displays the URL and filename to an apt package
#    that is to be downloaded.
#
#    Copyright (C) 2023 Aetherinox
#
#    script requires apt-move to be installed

FETCH=/usr/lib/apt-move/fetch

#	clean up cache
sudo apt-get clean

if [ ! -f $FETCH ]; then
	echo 'Install apt-move, as:'
	echo ' # apt-get install apt-move'
	exit 2
fi

if [ -z "$1" ]; then
	echo 'Usage:'
	echo '  ' $0 '<package>'
	exit 1
fi

#	get url of package
url=$(sudo $FETCH -t $1 | tail -n 1)

#	filter out %2b with +
url="${url/\%2b/"+"}"
#	filter out %3a with :
url="${url/\%3a/":"}"

#	strip filename from url
filename="${url##*/}"

#	return filename
echo $filename

#	return url
echo $url